[package]
name = "bitter-boundaries"
version = "0.1.0"
authors = ["bencelaszlo <bencelaszlo@protonmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.22.3"
quicksilver = "0.3.20"
rand = "0.7.2"